<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'MQRedisSessionStorage\Module'                      => __DIR__ . '/Module.php',
  'MQRedisSessionStorage\Factory\RedisStorageFactory' => __DIR__ . '/src/Factory/RedisStorageFactory.php',
  'MQRedisSessionStorage\Storage\RedisStorage'        => __DIR__ . '/src/Storage/RedisStorage.php',
);
